import { CVData } from './types';

export const initialCVData: CVData = {
  language: 'en',
  personalInfo: {
    fullName: '',
    jobTitle: '',
    email: '',
    phone: '',
    location: '',
    linkedin: '',
    github: '',
    website: '',
  },
  level: 'Entry Level',
  summary: '',
  experience: [],
  projects: [],
  skills: '',
  education: [],
  certifications: []
};

export const translations = {
  en: {
    summary: 'SUMMARY',
    experience: 'EXPERIENCE',
    projects: 'PROJECTS',
    skills: 'SKILLS',
    education: 'EDUCATION',
    certifications: 'CERTIFICATIONS',
    demo: 'Demo',
    github: 'GitHub',
    settings: 'General Settings',
    cvLanguage: 'CV Language',
    vietnamese: 'Tiếng Việt',
    english: 'English',
    candidateLevel: 'Candidate Level',
    entryLevel: 'Entry Level (Fresh Graduate/Little Experience)',
    midLevel: 'Mid Level (Experienced)',
    seniorLevel: 'Senior Level (Expert/Manager)',
    personalInfo: 'Personal Information',
    fullName: 'Full Name',
    jobTitle: 'Job Title',
    email: 'Email',
    phone: 'Phone Number',
    linkedin: 'LinkedIn',
    githubLabel: 'GitHub',
    summaryTitle: 'Professional Summary',
    summaryPlaceholder: 'Write a short paragraph introducing yourself, career goals...',
    projectsTitle: 'Projects',
    add: 'Add',
    projectName: 'Project Name',
    roleShortDesc: 'Role / Short Description',
    startDate: 'Start Date',
    endDate: 'End Date',
    demoLink: 'Demo Link',
    githubLink: 'GitHub Link',
    projectDetails: 'Project Details (One point per line)',
    experienceTitle: 'Work Experience',
    company: 'Company',
    position: 'Position',
    jobDescription: 'Job Description (One point per line)',
    noExperience: 'No experience added yet.',
    skillsTitle: 'Skills',
    skillsDesc: 'Enter skills, one skill group per line',
    educationTitle: 'Education',
    institution: 'Institution/Organization',
    degree: 'Degree (Optional)',
    eduDetails: 'Details (One point per line)',
    certificationsTitle: 'Certifications',
    certName: 'Certification Name',
    certDate: 'Date',
    certLink: 'Link (Optional)',
    exportPDF: 'Export PDF',
    exporting: 'Exporting...',
    pdfError: 'An error occurred while exporting PDF. Please try again.',
    placeholders: {
      fullName: 'e.g. John Doe',
      jobTitle: 'e.g. Software Engineer',
      email: 'e.g. john.doe@example.com',
      phone: 'e.g. +1 234 567 890',
      location: 'e.g. New York, USA',
      linkedin: 'e.g. linkedin.com/in/johndoe',
      github: 'e.g. github.com/johndoe',
      website: 'e.g. johndoe.com',
      projectName: 'e.g. E-commerce Platform',
      role: 'e.g. Fullstack Developer',
      date: 'e.g. MM/YYYY',
      present: 'e.g. Present or MM/YYYY',
      link: 'e.g. https://...',
      projectDetails: 'e.g. Built a web system using React and Node.js...\nDesigned and managed data with PostgreSQL...',
      company: 'e.g. Tech Corp',
      position: 'e.g. Senior Developer',
      jobDescription: 'e.g. Developed new features...\nOptimized application performance...',
      skills: 'e.g. Languages: JavaScript, Python\nFrontend: React, Tailwind CSS\nBackend: Node.js, Express',
      institution: 'e.g. University of Technology',
      degree: 'e.g. Bachelor of Computer Science',
      eduDetails: 'e.g. Major: Software Engineering\nGPA: 3.8/4.0',
      certName: 'e.g. AWS Certified Solutions Architect',
    }
  },
  vi: {
    summary: 'TÓM TẮT',
    experience: 'KINH NGHIỆM LÀM VIỆC',
    projects: 'DỰ ÁN',
    skills: 'KỸ NĂNG',
    education: 'HỌC VẤN',
    certifications: 'CHỨNG CHỈ',
    demo: 'Demo',
    github: 'GitHub',
    settings: 'Cài đặt chung',
    cvLanguage: 'Ngôn ngữ CV',
    vietnamese: 'Tiếng Việt',
    english: 'English',
    candidateLevel: 'Cấp độ ứng viên',
    entryLevel: 'Entry Level (Mới ra trường/Ít kinh nghiệm)',
    midLevel: 'Mid Level (Có kinh nghiệm)',
    seniorLevel: 'Senior Level (Chuyên gia/Quản lý)',
    personalInfo: 'Thông tin cá nhân',
    fullName: 'Họ và tên',
    jobTitle: 'Vị trí ứng tuyển',
    email: 'Email',
    phone: 'Số điện thoại',
    linkedin: 'LinkedIn',
    githubLabel: 'GitHub',
    summaryTitle: 'Tóm tắt bản thân',
    summaryPlaceholder: 'Viết một đoạn ngắn giới thiệu về bản thân, mục tiêu nghề nghiệp...',
    projectsTitle: 'Dự án',
    add: 'Thêm',
    projectName: 'Tên dự án',
    roleShortDesc: 'Vai trò / Mô tả ngắn',
    startDate: 'Bắt đầu',
    endDate: 'Kết thúc',
    demoLink: 'Demo Link',
    githubLink: 'GitHub Link',
    projectDetails: 'Chi tiết dự án (Mỗi dòng một ý)',
    experienceTitle: 'Kinh nghiệm làm việc',
    company: 'Công ty',
    position: 'Vị trí',
    jobDescription: 'Mô tả công việc (Mỗi dòng một ý)',
    noExperience: 'Chưa có kinh nghiệm nào được thêm.',
    skillsTitle: 'Kỹ năng',
    skillsDesc: 'Nhập các kỹ năng, mỗi dòng một nhóm kỹ năng',
    educationTitle: 'Học vấn',
    institution: 'Trường/Tổ chức',
    degree: 'Bằng cấp (Tùy chọn)',
    eduDetails: 'Chi tiết (Mỗi dòng một ý)',
    certificationsTitle: 'Chứng chỉ',
    certName: 'Tên chứng chỉ',
    certDate: 'Thời gian',
    certLink: 'Link (Tùy chọn)',
    exportPDF: 'Xuất PDF',
    exporting: 'Đang xuất...',
    pdfError: 'Có lỗi xảy ra khi xuất PDF. Vui lòng thử lại.',
    placeholders: {
      fullName: 'VD: Nguyễn Văn A',
      jobTitle: 'VD: Kỹ sư phần mềm',
      email: 'VD: nguyenvana@example.com',
      phone: 'VD: 0901 234 567',
      location: 'VD: TP. Hồ Chí Minh, Việt Nam',
      linkedin: 'VD: linkedin.com/in/nguyenvana',
      github: 'VD: github.com/nguyenvana',
      website: 'VD: nguyenvana.com',
      projectName: 'VD: Hệ thống thương mại điện tử',
      role: 'VD: Lập trình viên Fullstack',
      date: 'VD: MM/YYYY',
      present: 'VD: Hiện tại hoặc MM/YYYY',
      link: 'VD: https://...',
      projectDetails: 'VD: Xây dựng hệ thống web sử dụng React và Node.js...\nThiết kế và quản lý dữ liệu với PostgreSQL...',
      company: 'VD: Công ty Công nghệ ABC',
      position: 'VD: Lập trình viên Senior',
      jobDescription: 'VD: Phát triển các tính năng mới...\nTối ưu hóa hiệu suất ứng dụng...',
      skills: 'VD: Ngôn ngữ: JavaScript, Python\nFrontend: React, Tailwind CSS\nBackend: Node.js, Express',
      institution: 'VD: Đại học Bách Khoa',
      degree: 'VD: Cử nhân Khoa học Máy tính',
      eduDetails: 'VD: Chuyên ngành: Kỹ thuật phần mềm\nGPA: 3.8/4.0',
      certName: 'VD: Chứng chỉ AWS Solutions Architect',
    }
  }
};
